[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "192.168.0.206"
port = "3306"
username = "root"
password = "Password1"
database = "api_demo"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"